//! Differential test: Rust `build_program` IR + GLSL renderer == Python, across a
//! spread of seeds and both op-count configs. Pins the KISS99 draw order and the
//! shader-text renderer against the Python source of truth.
//!
//! The fixture is generated by `rust/tools/gen_fixtures.py`. Regenerate it whenever
//! the IR or renderer intentionally changes.

use std::path::PathBuf;

use rdna3_kawpow::progpow::{self, Op};
use serde_json::Value;

fn op_repr(op: &Op) -> (&'static str, Vec<u64>) {
    match *op {
        Op::Global => ("global", vec![]),
        Op::Cache { src, dst, r } => ("cache", vec![src as u64, dst as u64, r as u64]),
        Op::Math { s1, s2, dst, r1, r2 } => (
            "math",
            vec![s1 as u64, s2 as u64, dst as u64, r1 as u64, r2 as u64],
        ),
        Op::DagMerge { dst, i, r } => ("dagmerge", vec![dst as u64, i as u64, r as u64]),
    }
}

fn json_op_repr(v: &Value) -> (String, Vec<u64>) {
    let arr = v.as_array().expect("op must be an array");
    let tag = arr[0].as_str().expect("op tag must be a string").to_string();
    let rest = arr[1..].iter().map(|x| x.as_u64().unwrap()).collect();
    (tag, rest)
}

#[test]
fn ir_and_glsl_match_python() {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "ir.json"]
        .iter()
        .collect();
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {path:?}: {e} (run rust/tools/gen_fixtures.py)"));
    let doc: Value = serde_json::from_str(&raw).expect("parse fixture json");

    let mut ops_checked = 0usize;
    let mut seeds_checked = 0usize;

    for cfg in doc["configs"].as_array().unwrap() {
        let name = cfg["name"].as_str().unwrap();
        let cnt_cache = cfg["cnt_cache"].as_u64().unwrap() as usize;
        let cnt_math = cfg["cnt_math"].as_u64().unwrap() as usize;

        for entry in cfg["seeds"].as_array().unwrap() {
            let seed = entry["seed"].as_u64().unwrap();
            let ops = progpow::build_program(seed, cnt_cache, cnt_math);

            // 1) IR (draw order) must match exactly.
            let exp_ops = entry["ops"].as_array().unwrap();
            assert_eq!(
                ops.len(),
                exp_ops.len(),
                "[{name} seed={seed}] op count differs"
            );
            for (idx, (op, exp)) in ops.iter().zip(exp_ops).enumerate() {
                let (tag, fields) = op_repr(op);
                let (exp_tag, exp_fields) = json_op_repr(exp);
                assert_eq!(tag, exp_tag, "[{name} seed={seed}] op {idx} tag");
                assert_eq!(fields, exp_fields, "[{name} seed={seed}] op {idx} fields");
                ops_checked += 1;
            }

            // 2) Rendered GLSL must be byte-identical.
            let glsl = progpow::render_loop_glsl(seed, &ops);
            let exp_glsl = entry["glsl"].as_str().unwrap();
            assert_eq!(glsl, exp_glsl, "[{name} seed={seed}] GLSL renderer differs");

            seeds_checked += 1;
        }
    }

    assert!(seeds_checked >= 100, "fixture too small ({seeds_checked})");
    eprintln!("differential: {seeds_checked} seeds, {ops_checked} ops, GLSL all matched");
}
